import { h } from "koishi";
import { ChartInfo } from "../types";
import MusicInfo from "../types/music";

const colors = [
  "111, 212, 61",
  "248, 183, 9",
  "255, 129, 141",
  "159, 81, 220",
  "219, 170, 255",
];

/**
 * Generate a base table (定数表) for the given charts.
 * @param musics Musics with their charts to draw
 * @param base Base to display on the title
 * @returns Image generated by Puppeteer
 */
export function drawBaseTable(
  musics: { musicInfo: MusicInfo; chart: ChartInfo }[],
  base: string
): h {
  // Group musics by their base,
  // and convert them into HTML elements.
  const bases: Record<string, h[]> = {};
  musics.forEach((music) => {
    const base = music.chart.ds.toFixed(1);

    if (!bases[base]) bases[base] = [];
    bases[base].push(
      <div
        class="music"
        style={`background-color: rgb(${colors[music.chart.order]})`}
      >
        <img
          class="cover"
          src={this.ctx.maimaidxSongCover.getCover(music.musicInfo.id)}
        />
        {music.musicInfo.type === "DX" ? (
          <img
            class="deluxe"
            src={`${this.config.assetsPath}/mai/pic/DX.png`}
          />
        ) : (
          ""
        )}
      </div>
    );
  });

  // Convert grouped music HTML into parent
  // HTML element.
  const baseContainers = [];
  for (let base in bases) {
    baseContainers.push(
      <div class="base-level-box">
        <p class="base-text">{base}</p>
        <div class="base-music-box">{bases[base]}</div>
      </div>
    );
  }

  return (
    <html
      style="
        width: 1500px;
        position: relative;
        background: linear-gradient(rgb(203, 162, 253), rgb(251, 244, 127));
        margin: 0;
      "
    >
      <head>
        <style>
          {`
            @font-face {
              font-family: "torus";
              src: url("${this.config.assetsPath}/Torus SemiBold.otf");
            }
            @font-face {
              font-family: "siyuan";
              src: url("${this.config.assetsPath}/SourceHanSansSC-Bold.otf");
            }
            .base-level-box {
              width: 100%;
              display: flex;
              flex-wrap: nowrap;
              margin: 25px 0;
            }
            .base-text {
              margin: 0 25px 0 40px;
              font-family: siyuan;
              font-size: 50px;
              text-align: right;
            }
            .base-music-box {
              flex-grow: 1;
              margin-right: 40px;
              display: flex;
              flex-wrap: wrap;
            }
            .music {
              width: 75px;
              height: 75px;
              position: relative;
              margin: 5px;
            }
            .cover {
              width: 65px;
              height: 65px;
              position: absolute;
              left: 5px;
              top: 5px;
            }
            .deluxe {
              width: 44px;
              height: 16px;
              position: absolute;
              right: 0;
            }
          `}
        </style>
      </head>
      <img
        src={`${this.config.assetsPath}/mai/pic/top.png`}
        style="width: 100%; position: absolute; z-index: -1"
      />

      <div
        style="
          width: 100%;
          display: flex;
          flex-flow: column nowrap;
          align-items: center;
        "
      >
        <h1 style="margin: 150px 0 100px 0; font-family: siyuan; font-size: 65px">
          Level.{base}&nbsp;&nbsp;&nbsp;定数表
        </h1>
        {baseContainers}
        <div style="width: 100%; margin-bottom: 290px"></div>
      </div>

      <p
        style="
          width: 100%;
          position: absolute;
          bottom: 18px;
          margin: 0;
          z-index: 0;
          text-align: center;
          color: white;
          font-family: torus;
          font-size: 25px;
          text-shadow: 0 0 2px purple;
        "
      >
        Designed by Yuri-YuzuChaN & BlueDeer233 | Generated by{" "}
        {this.config.botName} BOT
      </p>
      <img
        src={`${this.config.assetsPath}/mai/pic/UI_CMN_TrackStart_MugenMap.png`}
        style="width: 100%; position: absolute; bottom: 0; z-index: -1"
      />
    </html>
  );
}
