import { h } from "koishi";
import { ChartInfo, MusicInfo } from "../types";

const category = {
  "流行&动漫": "anime",
  舞萌: "maimai",
  "niconico & VOCALOID": "niconico",
  东方Project: "touhou",
  其他游戏: "game",
  "音击&中二节奏": "ongeki",
};

/**
 * Render a simplified image of music info.
 * @param music Music object to draw
 * @param charts Charts of the music
 * @returns An image generated by Puppeteer
 */
export function drawMusicSimple(music: MusicInfo, charts: ChartInfo[]): h {
  let chartsH = charts.map((chart) => (
    <p
      style={
        chart.order === 4
          ? "width: 82px; margin: 0 13px 0 0; color: rgb(195, 70, 231)"
          : "width: 82px; margin: 0 13px 0 0"
      }
    >
      {chart.ds.toFixed(1)}
    </p>
  ));

  return (
    <html
      style="
        width: 700px;
        height: 1000px;
        margin: 0;
      "
    >
      <head>
        <style>
          {`
            @font-face {
              font-family: "torus";
              src: url("${this.config.assetsPath}/Torus SemiBold.otf");
            }
            @font-face {
              font-family: "siyuan";
              src: url("${this.config.assetsPath}/SourceHanSansSC-Bold.otf");
            }
          `}
        </style>
      </head>
      <div
        style={`
          position: absolute;
          width: 700px;
          height: 1000px;
          background-image: url(${this.config.assetsPath}/mai/pic/music_bg.png);
          margin: 0;
        `}
      >
        <img
          style="position: absolute; left: 150px; top: 170px"
          src={`${this.config.assetsPath}/mai/pic/music-${
            category[music.genre]
          }.png`}
        />
        <img
          style="
            position: absolute;
            left: 170px;
            top: 260px;
            width: 360px;
            height: 360px;
          "
          src={this.ctx.maimaidxSongCover.getCover(music.id)}
        />
        <img
          style="
            position: absolute;
            left: 435px;
            top: 585px;
            width: 94px;
            height: 35px;
          "
          src={`${this.config.assetsPath}/mai/pic/${music.type}.png`}
        />
        <hr
          style="
            position: absolute;
            left: 150px;
            top: 710px;
            width: 400px;
            height: 2px;
            background-color: white;
            margin: 0;
            border: none;
          "
        />
        <p
          style="
            position: absolute;
            left: 159px;
            top: 179px;
            width: 82px;
            height: 36px;
            line-height: 36px;
            font-size: 24px;
            font-family: torus;
            color: white;
            text-align: center;
            margin: 0;
          "
        >
          {music.id}
        </p>
        <p
          style="
            position: absolute;
            left: 279px;
            top: 179px;
            width: 262px;
            height: 36px;
            line-height: 36px;
            font-size: 22px;
            font-family: siyuan;
            color: white;
            text-align: center;
            margin: 0;
          "
        >
          {music.genre}
        </p>
        <p
          style="
            position: absolute;
            left: 0;
            top: 645px;
            width: 700px;
            height: 30px;
            line-height: 30px;
            font-size: 30px;
            font-family: siyuan;
            color: white;
            text-shadow: 1px 1px 0 black;
            text-align: center;
            margin: 0;
          "
        >
          {music.title}
        </p>
        <p
          style="
            position: absolute;
            left: 0;
            top: 684px;
            width: 700px;
            height: 12px;
            line-height: 12px;
            font-size: 12px;
            font-family: siyuan;
            color: white;
            text-shadow: 1px 1px 0 black;
            text-align: center;
            margin: 0;
          "
        >
          {music.artist}
        </p>
        <div
          style="
            position: absolute;
            left: 150px;
            top: 717px;
            width: 400px;
            height: 15px;
            line-height: 15px;
            font-size: 15px;
            font-family: siyuan;
            color: white;
            text-shadow: 1px 1px 0 black;
          "
        >
          <p style="float: left; margin: 0">Version: {music.version}</p>
          <p style="float: right; margin: 0">BPM: {music.bpm}</p>
        </div>
        <div
          style="
            display: flex;
            position: absolute;
            left: 119px;
            top: 784px;
            width: 481px;
            height: 62px;
            line-height: 62px;
            font-size: 25px;
            font-family: torus;
            color: white;
            text-align: center;
          "
        >
          {chartsH}
        </div>
        <p
          style="
            position: absolute;
            left: 0;
            top: 975px;
            width: 700px;
            height: 14px;
            line-height: 14px;
            font-size: 14px;
            font-family: torus;
            color: white;
            text-shadow: 0 0 2px purple;
            text-align: center;
            margin: 0;
          "
        >
          Designed by Yuri-YuzuChaN | Generated by {this.config.botName} BOT
        </p>
      </div>
    </html>
  );
}

/**
 * Render an image of music info.
 * @param music Music object to draw
 * @param charts Charts of the music
 * @returns An image generated by Puppeteer
 */
export function drawMusic(music: MusicInfo, charts: ChartInfo[]): h {
  let chartsInfo = [];
  let charters = [];

  charts.forEach((chart) => {
    chartsInfo.push(
      <div style="display: flex; width: 100%; height: 107px; margin-bottom: 3px">
        <p
          style={`
            width: 200px;
            margin: 0 3px 0 0;
            padding-top: 47px;
            line-height: 30px;
            font-size: 30px;
            ${chart.order === 4 ? "" : "color: white;"}
          `}
        >
          {chart.level}({chart.ds.toFixed(1)})
        </p>
        <p style="width: 187px; margin: 0 3px 0 0">
          {chart.stat?.fit_diff !== undefined
            ? chart.stat.fit_diff.toFixed(2)
            : "-"}
        </p>
        <p style="width: 172px; margin: 0 3px 0 0">
          {chart.notes.reduce((a, b) => a + b, 0)}
        </p>
        <p style="width: 172px; margin: 0 3px 0 0">{chart.notes[0]}</p>
        <p style="width: 172px; margin: 0 3px 0 0">{chart.notes[1]}</p>
        <p style="width: 172px; margin: 0 3px 0 0">{chart.notes[2]}</p>
        <p style="width: 172px; margin: 0 3px 0 0">
          {chart.notes.length < 5 ? "0" : chart.notes[3]}
        </p>
        <p style="width: 172px; margin: 0 3px 0 0">
          {chart.notes.length < 5 ? chart.notes[3] : chart.notes[4]}
        </p>
      </div>
    );

    if (chart.order > 1)
      charters.push(
        <p
          style={`width: 414px; margin: 0; ${
            chart.order === 4 ? "color: rgb(140, 44, 213);" : ""
          }`}
        >
          {chart.charter}
        </p>
      );
  });

  return (
    <html
      style="
        width: 1800px;
        height: 1600px;
        margin: 0;
      "
    >
      <head>
        <style>
          {`
            @font-face {
              font-family: "torus";
              src: url("${this.config.assetsPath}/Torus SemiBold.otf");
            }
            @font-face {
              font-family: "siyuan";
              src: url("${this.config.assetsPath}/SourceHanSansSC-Bold.otf");
            }
          `}
        </style>
      </head>
      <div
        style={`
            position: absolute;
            width: 1800px;
            height: 1600px;
            background-image: url(${this.config.assetsPath}/mai/pic/song_bg.png);
            margin: 0;
          `}
      >
        <img
          style="
            position: absolute;
            left: 205px;
            top: 305px;
            width: 400px;
            height: 400px;
          "
          src={this.ctx.maimaidxSongCover.getCover(music.id)}
        />
        <img
          style="
            position: absolute;
            left: 1340px;
            top: 590px;
            width: 250px;
            height: 120px;
          "
          src={`${this.config.assetsPath}/mai/pic/${music.version}.png`}
        />
        <img
          style="
            position: absolute;
            left: 1150px;
            top: 643px;
            width: 140px;
            height: 52px;
          "
          src={`${this.config.assetsPath}/mai/pic/${music.type}.png`}
        />
        <p
          style="
            position: absolute;
            left: 640px;
            top: 330px;
            line-height: 40px;
            font-size: 40px;
            font-family: siyuan;
            color: rgb(140, 44, 213);
            margin: 0;
          "
        >
          {music.title}
        </p>
        <p
          style="
            position: absolute;
            left: 640px;
            top: 410px;
            line-height: 30px;
            font-size: 30px;
            font-family: siyuan;
            color: rgb(140, 44, 213);
            margin: 0;
          "
        >
          {music.artist}
        </p>
        <p
          style="
            position: absolute;
            left: 705px;
            top: 528px;
            line-height: 40px;
            font-size: 40px;
            font-family: torus;
            color: rgb(140, 44, 213);
            margin: 0;
          "
        >
          {music.bpm}
        </p>
        <p
          style="
            position: absolute;
            left: 640px;
            top: 645px;
            line-height: 40px;
            font-size: 40px;
            font-family: torus;
            color: rgb(140, 44, 213);
            margin: 0;
          "
        >
          ID {music.id}
        </p>
        <p
          style="
            position: absolute;
            left: 770px;
            top: 650px;
            width: 400px;
            line-height: 30px;
            font-size: 30px;
            font-family: siyuan;
            color: rgb(140, 44, 213);
            text-align: center;
            margin: 0;
          "
        >
          {music.genre}
        </p>
        <div
          style="
            display: flex;
            flex-direction: column;
            position: absolute;
            left: 180px;
            top: 893px;
            width: 1443px;
            height: 547px;
            line-height: 107px;
            font-size: 40px;
            font-family: torus;
            color: rgb(140, 44, 213);
            text-align: center;
          "
        >
          {chartsInfo}
        </div>
        <div
          style="
            display: flex;
            position: absolute;
            left: 378px;
            top: 1483px;
            width: 1242px;
            height: 80px;
            line-height: 80px;
            font-size: 22px;
            font-family: siyuan;
            color: white;
            text-align: center;
          "
        >
          {charters}
        </div>
      </div>
    </html>
  );
}
