import { h } from "koishi";
import { Config } from "..";
import { ChartInfo, MusicInfo } from "../types";

/**
 * Draw a list of music.
 * @param config Config object of the plugin
 * @param musics Music to draw
 * @returns Music list image generated by Puppeteer
 */
export function drawSearchResults(config: Config, musics: MusicInfo[]): h {
  const entries = musics.map((music) => (
    <tr>
      <td style="font-family: torus">{music.id}</td>
      <td>{music.title}</td>
    </tr>
  ));

  return (
    <html>
      <head>
        <style>
          {`
              td {
                padding: 0.5em 2em;
              }
              table,
              th,
              td {
                border: 2px solid #c473ff;
              }
              @font-face {
                font-family: "torus";
                src: url("${config.assetsPath}/Torus SemiBold.otf");
              }
              @font-face {
                font-family: "siyuan";
                src: url("${config.assetsPath}/SourceHanSansSC-Bold.otf");
              }
            `}
        </style>
      </head>
      <table style="font-size: 20px; border-collapse: collapse; font-family: siyuan; color: #8c2cd5">
        <thead>
          <tr>
            <th>乐曲ID</th>
            <th>曲名</th>
          </tr>
        </thead>
        <tbody>{entries}</tbody>
      </table>
    </html>
  );
}

/**
 * Draw a list of music, with music charter involved.
 * @param config Config object of the plugin
 * @param musics Music to draw
 * @returns Music list image generated by Puppeteer
 */
export function drawSearchResultsWithArtist(
  config: Config,
  musics: MusicInfo[]
): h {
  const entries = musics.map((music) => (
    <tr>
      <td style="font-family: torus">{music.id}</td>
      <td>{music.title}</td>
      <td>{music.artist}</td>
    </tr>
  ));

  return (
    <html>
      <head>
        <style>
          {`
              td {
                padding: 0.5em 2em;
              }
              table,
              th,
              td {
                border: 2px solid #c473ff;
              }
              @font-face {
                font-family: "torus";
                src: url("${config.assetsPath}/Torus SemiBold.otf");
              }
              @font-face {
                font-family: "siyuan";
                src: url("${config.assetsPath}/SourceHanSansSC-Bold.otf");
              }
            `}
        </style>
      </head>
      <table style="font-size: 20px; border-collapse: collapse; font-family: siyuan; color: #8c2cd5">
        <thead>
          <tr>
            <th>乐曲ID</th>
            <th>曲名</th>
            <th>曲师</th>
          </tr>
        </thead>
        <tbody>{entries}</tbody>
      </table>
    </html>
  );
}

/**
 * Draw a list of music, with chart order involved.
 * @param config Config object of the plugin
 * @param musics Corresponding music and chart to draw
 * @returns Music list image generated by Puppeteer
 */
export function drawSearchResultsWithChart(
  config: Config,
  musics: { musicInfo: MusicInfo; chart: ChartInfo }[]
): h {
  const backgroundColors = [
    "#6fd43d",
    "#f8b709",
    "#ff818d",
    "#9f51dc",
    "#dbaaff",
  ];

  const entries = musics.map((music) => (
    <tr
      style={`background-color: ${backgroundColors[music.chart.order]}; ${
        music.chart.order === 4 ? "color: #8c2cd5;" : ""
      }`}
    >
      <td style="font-family: torus">{music.musicInfo.id}</td>
      <td>{music.musicInfo.title}</td>
      <td>{music.chart.charter}</td>
    </tr>
  ));

  return (
    <html>
      <head>
        <style>
          {`
              td {
                padding: 0.5em 2em;
              }
              table,
              th,
              td {
                border: 2px solid #c473ff;
              }
              @font-face {
                font-family: "torus";
                src: url("${config.assetsPath}/Torus SemiBold.otf");
              }
              @font-face {
                font-family: "siyuan";
                src: url("${config.assetsPath}/SourceHanSansSC-Bold.otf");
              }
            `}
        </style>
      </head>
      <table style="font-size: 20px; border-collapse: collapse">
        <thead style="font-family: siyuan; color: #8c2cd5">
          <tr>
            <th>乐曲ID</th>
            <th>曲名</th>
            <th>谱师</th>
          </tr>
        </thead>
        <tbody style="font-family: siyuan; color: white">{entries}</tbody>
      </table>
    </html>
  );
}
